### ISSUE TITLE
Make the test report clickable

### ISSUE THREAD

**Issue by marmidr** [offa/NBCndUnit#1]
Hello,
first of all, I want to thank you for your great job!
Just a few days after I started working with CppUTest framework I found your NB plugin, easy to install, easy to use.
Only one thing is not working as expected - previously I used to make unit tests with NB simple testing feature, and every time some test failed I was able to navigate to the file and test simply by double clicking on the report (or the context menu: Go to Source).

With your plugin this is not possible, even if test failure location is specified in the report.
I'm using the latest official NB  release, 8.0.2. Since I'm not Java developer I cannot help you improve this plugin, but I can offer you my services as a tester :)

Kindly regards,
Mariusz Midor

**Comment by offa** [comment]
Thanks @mmidor.

I'm currently on this issue - unfortunately without a solution yet. I also have asked this question in the NB Mailinglist, but no solution there (yet) too.

**Comment by offa** [comment]
Here's an update:

The modules shipped with NetBeans 8.0.x do not allow to add the Go to Source Action, since there's no public API available for it.

The current NetBeans codebase – as in the official Mercurial repository – has many improvements in this area. That's good! Unfortunately I don't know when it will arrive. Maybe it's 8.1, 8.x or not before NB 9.

There are two practicable workarounds for this problem now:
1. Rewriting the  necessary parts of the Cnd Testrunner (but this results in a huge code duplication, maintenance efforts etc., it's also a huge amount of work to do)
2. Use reflection to “hack” the testsession objects, replacing one part with a custom one (not nice, but it has no negative effects and doesn't affect other modules)

I guess it's clear, the former one is not realistic.

So finally I'm working on the reflection based approach. I'll push it's branch soon (but it's still WIP and not ready for public usage!).

**Comment by offa** [comment]
I've pushed a new branch gotosource for the “Go to Source” development.

Note, it's still in early development.

---

Some info about the first push:
- First implementation for _CppUTest_ tests
- Go to source for testcases / -suites (jumps through callstack isn't fully implemented yet)
- ~~Testsuits will jump to the source of it's first _executed_ testcase (I'll change this in the future)~~

**Comment by offa** [comment]
Jump to Testsuite implemented in a925fe5254cc98c99b7cf355c8c7efcf9db06d89.

**Comment by marmidr** [comment]
Hello @offa,
it's a pleasure to hear that you still working on it, event if current NB architecture is against you :)
I will monitor changes you making.

BTW currently I'm working on the CppUTest itself, implementing some small features that will help running the tests separately from CMake/CTest.
The change is quite simple, but the authors of the library are restrictive so it's hard to persuade them it's good enough to merge with the trunk.

**Comment by offa** [comment]
It's not the architecture (which is really great), it's just one method that's missing.

However, NB devs have done a good job here, the next release will contain some great improvements, which solve the problem :+1: . And until then i have a workaround.

**Comment by offa** [comment]
Go to source is now implemented for all three frameworks.

**Comment by marmidr** [comment]
I'm happy to see that the issue has been solved so fast.
Are you going to publish update for the plugin?

**Comment by offa** [comment]
> Are you going to publish update for the plugin?

Of course, but before this i have some other todo's for the next version. Eg. the jump-to-callstack is not yet implemented (but already in development).

If you want, you can checkout the master branch and build it yourself for testing. If you are not familiar with building Netbeans modules i also can upload a ready to use snapshot for you.

**Comment by marmidr** [comment]
That's what I'm asking for :) I am not familiar with Java, not mentioning the modules for NB.
If this is not a problem, you can prepare some binaries for me and I will test them tomorrow.

**Comment by offa** [comment]
No problem, you can download the NBM of the current master branch [here](http://www49.zippyshare.com/v/ny73iT14/file.html).

**Sha256 sum:**

```
15d7ec7f9b568fa69d873d275e10adaa2acaf0ea45a7745580b5491243c5caa3  NBCndUnit-0.5.2-SNAPSHOT.nbm
```

Please note: it's not signed yet.

**Comment by marmidr** [comment]
For CppUTest works great! Thanks!

**Comment by offa** [comment]
Good to hear, thank you! :+1:
