### ISSUE TITLE
Running Debug Test results in Sigtrap window

### ISSUE THREAD

**Issue by dellgreen** [offa/NBCndUnit#5]
I have a number of developers with different native projects who have reported the inability to debug tests using google test or cppunit. Don't know if this is plugin related or netbeans related.

If they right click on a test and run "Test" everything runs fine, all tests run, If they right click on a test and run "Debug Test" then a sigtrap window is displayed. Screen shots are attached.

<img width="170" alt="screen shot 2016-01-09 at 09 36 42" src="https://cloud.githubusercontent.com/assets/12861109/12215448/b1feb614-b6b4-11e5-8951-ab497ded3ad1.png">

All using various iterations of Netbeans 8.1 including latest (as of time of post), on Mac OS X 10.9.5. Java Projects work fine.

<img width="615" alt="screen shot 2016-01-09 at 09 28 04" src="https://cloud.githubusercontent.com/assets/12861109/12215441/723df5d0-b6b4-11e5-8dbb-5d25a137a6df.png">

**Comment by offa** [comment]
I've tested using some CppUTest and gtest suites, there debugging works trouble-free, at least on linux (gcc 5.3, gdb 7.10). Can you reproduce this with a very simple test case? You can also try from commandline, without any ide - just to verify it's not a problem of debugger etc.

At first glance it looks like a NB or tool related problem: the debugging isn't changed nor implemented by this plugin - the default behaviour, provided by the testrunner is used. Since cppunit seems affected too, it's probable a more general issue.

It could also be a general debugger-related problem or an compatibility issue; NB calls the debugger - eg. gdb -  and doesn't implement C/C++ debugging itself. From a first search: [here](http://stackoverflow.com/questions/3475262/what-causes-a-sigtrap-in-a-debug-session) and [here](http://stackoverflow.com/questions/9809413/program-received-signal-sigtrap-trace-breakpoint-trap).

However, it's a good idea to file a [**Netbeans issue**](https://netbeans.org/community/issues.html).

**Comment by offa** [comment]
@dellgreen I was unable to reproduce this bug so far (have no mac os x btw.). As stated above, the debug behaviour is not provided by this plugin and from what I can see out of your description it's more likely a tool or netbeans related problem. Therefore I'll close here -- but feel free to reopen or post any further informations.

_If not done yet, please file an issue at netbeans (link see above)._
